//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Revision()
        {
            this.Inspeccion = new HashSet<Inspeccion>();
        }
    
        public int IdRevision { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccion { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
