//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiVehiculos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RevisionVehiculosEntities : DbContext
    {
        public RevisionVehiculosEntities()
            : base("name=RevisionVehiculosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inspeccion> Inspeccion { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Revision> Revision { get; set; }
        public virtual DbSet<TipoRevision> TipoRevision { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
